### ISSUE TITLE
不停的报错

### ISSUE THREAD

**Issue by zeroBugL** [amggg/YXing#17]
E/ImageAnalysisAnalyzer: Failed to acquire image.
    java.lang.IllegalStateException: maxImages (4) has already been acquired, call #close before acquiring more.
        at android.media.ImageReader.acquireNextImage(ImageReader.java:502)
        at android.media.ImageReader.acquireLatestImage(ImageReader.java:386)
        at androidx.camera.core.AndroidImageReaderProxy.acquireLatestImage(AndroidImageReaderProxy.java:56)
        at androidx.camera.core.SafeCloseImageReaderProxy.acquireLatestImage(SafeCloseImageReaderProxy.java:67)
        at androidx.camera.core.ImageAnalysisNonBlockingAnalyzer.acquireImage(ImageAnalysisNonBlockingAnalyzer.java:65)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.onImageAvailable(ImageAnalysisAbstractAnalyzer.java:58)
        at androidx.camera.core.SafeCloseImageReaderProxy.lambda$setOnImageAvailableListener$1$SafeCloseImageReaderProxy(SafeCloseImageReaderProxy.java:173)
        at androidx.camera.core.SafeCloseImageReaderProxy$$ExternalSyntheticLambda1.onImageAvailable(Unknown Source:4)
        at androidx.camera.core.AndroidImageReaderProxy.lambda$setOnImageAvailableListener$0$AndroidImageReaderProxy(AndroidImageReaderProxy.java:139)

**Comment by amggg** [comment]
集成的哪个版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月30日(周二) 晚上11:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [amggg/YXing] 不停的报错 (Issue #17)




 
E/ImageAnalysisAnalyzer: Failed to acquire image.
 java.lang.IllegalStateException: maxImages (4) has already been acquired, call #close before acquiring more.
 at android.media.ImageReader.acquireNextImage(ImageReader.java:502)
 at android.media.ImageReader.acquireLatestImage(ImageReader.java:386)
 at androidx.camera.core.AndroidImageReaderProxy.acquireLatestImage(AndroidImageReaderProxy.java:56)
 at androidx.camera.core.SafeCloseImageReaderProxy.acquireLatestImage(SafeCloseImageReaderProxy.java:67)
 at androidx.camera.core.ImageAnalysisNonBlockingAnalyzer.acquireImage(ImageAnalysisNonBlockingAnalyzer.java:65)
 at androidx.camera.core.ImageAnalysisAbstractAnalyzer.onImageAvailable(ImageAnalysisAbstractAnalyzer.java:58)
 at androidx.camera.core.SafeCloseImageReaderProxy.lambda$setOnImageAvailableListener$1$SafeCloseImageReaderProxy(SafeCloseImageReaderProxy.java:173)
 at androidx.camera.core.SafeCloseImageReaderProxy$$ExternalSyntheticLambda1.onImageAvailable(Unknown Source:4)
 at androidx.camera.core.AndroidImageReaderProxy.lambda$setOnImageAvailableListener$0$AndroidImageReaderProxy(AndroidImageReaderProxy.java:139)
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
