### ISSUE TITLE
我报这个

### ISSUE THREAD

**Issue by StevenZhangHl** [amggg/YXing#18]
java.lang.IllegalStateException: CameraX is not configured properly. The most likely cause is you did not include a default implementation in your build such as 'camera-camera2'.
        at androidx.camera.core.CameraX.getOrCreateInstance(CameraX.java:328)
        at androidx.camera.lifecycle.ProcessCameraProvider.getInstance(ProcessCameraProvider.java:156)
        at com.yxing.ScanCodeActivity.bindCameraUseCases(ScanCodeActivity.kt:105)
        at com.yxing.ScanCodeActivity.access$bindCameraUseCases(ScanCodeActivity.kt:24)
        at com.yxing.ScanCodeActivity$initData$1.run(ScanCodeActivity.kt:54)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7584)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
已经加了还是报错
![image](https://user-images.githubusercontent.com/7867862/150911964-47e9ccc9-cf4c-4e18-bd42-7ff939ff9046.png)

**Comment by amggg** [comment]
库里面有包含camera2的依赖， 不需要再次添加依赖。
