### ISSUE TITLE
最新版本v2.0.1扫码之后拿不到返回结果

### ISSUE THREAD

**Issue by GitXwj** [amggg/YXing#29]
报错信息：

paused 10.075ms total 29.302ms
2023-07-28 15:28:05.907 4002-4050/com.yjt.zyj E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: com.yjt.zyj, PID: 4002
    java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:631)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:165)
        at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
        at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
        at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:176)
        at com.google.zxing.MultiFormatReader.decode(MultiFormatReader.java:57)
        at com.yxing.ScanCodeAnalyzer.analyze(ScanCodeAnalyzer.kt:150)
        at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$2(ImageAnalysis.java:481)
        at androidx.camera.core.ImageAnalysis$$ExternalSyntheticLambda0.analyze(D8$$SyntheticClass)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$androidx-camera-core-ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:286)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
    
    
    --------- beginning of system

**Comment by amggg** [comment]
这个错误是方法没找到， 检查一下你自己项目中的zxing版本是不是和库中的有冲突。
