### ISSUE TITLE
启动扫描activity报错

### ISSUE THREAD

**Issue by steven945** [amggg/YXing#4]
![image](https://user-images.githubusercontent.com/7867862/109763190-b0b52980-7c2c-11eb-8613-54b75116febf.png)
报错原因时说ScanCodeActivity没有设置theme

**Comment by amggg** [comment]
把你项目中的主题&nbsp; parent替换成带AppCompat的
。

---原始邮件---
发件人: "steven945"<notifications@github.com&gt;
发送时间: 2021年3月3日(周三) 下午2:29
收件人: "amggg/YXing"<YXing@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [amggg/YXing] 启动扫描activity报错 (#4)




 

 报错原因时说ScanCodeActivity没有设置theme

**Comment by steven945** [comment]
现在又爆这个错误
 Process: com.meix, PID: 20788
    java.lang.VerifyError: Verifier rejected class com.yxing.DecodeFormatManager: void com.yxing.DecodeFormatManager.<clinit>() failed to verify: void com.yxing.DecodeFormatManager.<clinit>(): [0x2] register v0 has type Precise Reference: com.google.zxing.BarcodeFormat but expected Reference: java.lang.Enum (declaration of 'com.yxing.DecodeFormatManager' appears in /data/app/com.meix-d0QzlDEpH0IJM8nMK4cmIA==/base.apk!classes27.dex)
        at com.yxing.ScanCodeAnalyzer.initReader(ScanCodeAnalyzer.kt:74)
        at com.yxing.ScanCodeAnalyzer.<init>(ScanCodeAnalyzer.kt:18)
        at com.yxing.ScanCodeActivity$bindCameraUseCases$1.run(ScanCodeActivity.kt:128)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7584)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
