### ISSUE TITLE
报错，找不到原因

### ISSUE THREAD

**Issue by ylmyg** [amggg/YXing#8]
new RxPermissions(MainActivity.this)
                        .requestEachCombined(Manifest.permission.CAMERA)
                        .subscribe(new Observer<Permission>() {
                            @Override
                            public void onSubscribe(@NonNull Disposable d) {
                            }

                            @Override
                            public void onNext(@NonNull Permission permission) {
                                if (permission.granted) {
                                    ScanCodeConfig.create(MainActivity.this)                                    
                                            .setStyle(ScanStyle.NONE)
                                            .setPlayAudio(true)
                                            .buidler()
                                            //跳转扫码页   扫码页可自定义样式
                                            .start(SaomaActivity.class);
                                }
                            }

                            @Override
                            public void onError(@NonNull Throwable e) {
                            }

                            @Override
                            public void onComplete() {
                            }
                        });
===========================================
public class SaomaActivity extends ScanCodeActivity {

    @Override
    public int getLayoutId() {
        return R.layout.activity_saoma;
    }

    @Override
    public void initData() {
        super.initData();
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        //接收扫码结果
        if (resultCode == RESULT_OK && requestCode == ScanCodeConfig.QUESTCODE && data != null) {
            Bundle extras = data.getExtras();
            if (extras != null) {
                String code = extras.getString(ScanCodeConfig.CODE_KEY);
                ToastUtils.showLong(String.format("%s%s", "结果： ", code));
            }
        }
    }
}
=========================
就报错 找不到解决办法
java.lang.AbstractMethodError: abstract method "java.lang.Object androidx.camera.core.impl.CameraFactory.getCameraManager()"
        at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$9$CameraX(CameraX.java:566)
        at androidx.camera.core.-$$Lambda$CameraX$PyTMqE8rSnFsLpsANtL2ojEI5QI.run(Unknown Source:10)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)

**Comment by amggg** [comment]
1.检查引用的是不是最新版。
2.检查自己项目中是否有引用其他版本的camera。
3.下载Demo， 里面有这个实现。



---原始邮件---
发件人: "ylmyg"<notifications@github.com&gt;
发送时间: 2021年3月5日(周五) 上午10:33
收件人: "amggg/YXing"<YXing@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [amggg/YXing] 报错，找不到原因 (#8)




 
new RxPermissions(MainActivity.this)
 .requestEachCombined(Manifest.permission.CAMERA)
 .subscribe(new Observer() {
 @override
 public void onSubscribe(@nonnull Disposable d) {
 }
                         @Override                         public void onNext(@NonNull Permission permission) {                             if (permission.granted) {                                 ScanCodeConfig.create(MainActivity.this)                                                                             .setStyle(ScanStyle.NONE)                                         .setPlayAudio(true)                                         .buidler()                                         //跳转扫码页   扫码页可自定义样式                                         .start(SaomaActivity.class);                             }                         }                         @Override                         public void onError(@NonNull Throwable e) {                         }                         @Override                         public void onComplete() {                         }                     });  
===========================================
 public class SaomaActivity extends ScanCodeActivity {
 @Override public int getLayoutId() {     return R.layout.activity_saoma; } @Override public void initData() {     super.initData(); } @Override protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {     super.onActivityResult(requestCode, resultCode, data);     //接收扫码结果     if (resultCode == RESULT_OK &amp;&amp; requestCode == ScanCodeConfig.QUESTCODE &amp;&amp; data != null) {         Bundle extras = data.getExtras();         if (extras != null) {             String code = extras.getString(ScanCodeConfig.CODE_KEY);             ToastUtils.showLong(String.format("%s%s", "结果： ", code));         }     } }  
}
 
就报错 找不到解决办法
 java.lang.AbstractMethodError: abstract method "java.lang.Object androidx.camera.core.impl.CameraFactory.getCameraManager()"
 at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$9$CameraX(CameraX.java:566)
 at androidx.camera.core.-$$Lambda$CameraX$PyTMqE8rSnFsLpsANtL2ojEI5QI.run(Unknown Source:10)
 at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:784)

**Comment by ylmyg** [comment]
能加个Q85446450么？换了项目里面的demo还是这个错误，应该是冲突，那这样不是很难解决
